### ISSUE TITLE
Hello, are you the developer of Tobii python API?

### ISSUE THREAD

**Issue by leeweizhe1993** [ddetommaso/TobiiProGlasses2_PyCtrl#2]
How can I get in touch with you on Twitter, Email or other platform?

**Comment by ddetommaso** [comment]
Hi,

I am the developer of the TobiiProGlasses2_PyCtrl library which is an open-source Python wrapper to control the commercial product Tobii Pro Glasses 2 through the Tobii Pro Glasses 2 API.

Please write here only for issues related to the TobiiProGlasses2_PyCtrl. If you wanna keep in touch with me feel free to contact me on Linkedin at https://www.linkedin.com/in/davide-de-tommaso-3b850731/
