### ISSUE TITLE
Failed to stream video

### ISSUE THREAD

**Issue by bwang514** [ddetommaso/TobiiProGlasses2_PyCtrl#3]
Hi ddetommaso, thanks for sharing the code to control tobii glasses!

With your code I can stream the gaze data now but I failed to stream the scene camera video.

I got an error in this line of code.
ipv4_address = "192.168.71.50"
cap = cv2.VideoCapture("rtsp://%s/live/scene" % ipv4_address)
Does using ipv4 address here means the code can only work with wifi connection?
Since in streaming code we seem to use ipv6 I . (e.g. fe80::76fe:......)

Thanks!

**Comment by ddetommaso** [comment]
Hi @bwang514,
you are right, the code works only using IPv4 address.
I wasn't able to access any video streaming of the glasses with IPv6 address, even using VLC software.

What about your experience? Did you try to access the /live/scene using IPV6?

**Comment by FranzAlbers** [comment]
Hey @bwang514, 
i experienced the same issue while trying to stream the scene camera video.
I solved it by adding port 8554 to the call, which is mentioned in the tobii developers guide.

`cap = cv2.VideoCapture("rtsp://%s:8554/live/scene" % ipv4_address)`

**Comment by ddetommaso** [comment]
Hi @FranzAlbers,

this doesn't work for me. Are you using IPv6 address in you example or IPv4?
Please can you paste here the complete URI provided as argument to the VideoCapture?

**Comment by FranzAlbers** [comment]
I am using an IPv4 address and the Tobii Glasses are connected via Ethernet. I couldn't access the stream using IPv6 either. The complete line of code would be:

cap = cv2.VideoCapture("rtsp://192.168.0.121:8554/live/scene")`

Without the port in the URI the connection is refused. The glasses are on 1.25.3-citronkola.

**Comment by ddetommaso** [comment]
Hi @FranzAlbers,

thank you so much for your feedback. I run successfully the video streaming with LAN using IPv4!!
I will change the code and the documentation in the following releases, before closing the issue.

Just to clarify, IPv4 with LAN is feasible only if a DHCP server is present in the network. In your example, the "192.168.0.121" is the address that the glasses receives from the DHCP server present in your network.

@bwang514: Did you try setting a DHCP server in your network and adding the port in the URI as suggested by @FranzAlbers ?

**Comment by ddetommaso** [comment]
closed eec39d13bfd1c9a650831e900d84195dd7f909af
